// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcMuGWdFyp2KcdqMLERWdmsvHiVZt8374',
    appId: '1:535905372792:web:a057a5347d2ccc09b9bb8d',
    messagingSenderId: '535905372792',
    projectId: 'wearth-370f1',
    authDomain: 'wearth-370f1.firebaseapp.com',
    databaseURL: 'https://wearth-370f1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wearth-370f1.firebasestorage.app',
    measurementId: 'G-4K4L47LZ45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTeXg7Lm7McnWmcpgIWbyWkXM9Uay7pSE',
    appId: '1:535905372792:android:43676947221bcdf2b9bb8d',
    messagingSenderId: '535905372792',
    projectId: 'wearth-370f1',
    databaseURL: 'https://wearth-370f1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wearth-370f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn4NyP8yqUQDGPCm9Ad1XBlOzBtocNQY4',
    appId: '1:535905372792:ios:029867163a25f764b9bb8d',
    messagingSenderId: '535905372792',
    projectId: 'wearth-370f1',
    databaseURL: 'https://wearth-370f1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wearth-370f1.firebasestorage.app',
    iosBundleId: 'com.wearth.wearth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn4NyP8yqUQDGPCm9Ad1XBlOzBtocNQY4',
    appId: '1:535905372792:ios:029867163a25f764b9bb8d',
    messagingSenderId: '535905372792',
    projectId: 'wearth-370f1',
    databaseURL: 'https://wearth-370f1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wearth-370f1.firebasestorage.app',
    iosBundleId: 'com.wearth.wearth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcMuGWdFyp2KcdqMLERWdmsvHiVZt8374',
    appId: '1:535905372792:web:334513c8dca2f56cb9bb8d',
    messagingSenderId: '535905372792',
    projectId: 'wearth-370f1',
    authDomain: 'wearth-370f1.firebaseapp.com',
    databaseURL: 'https://wearth-370f1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wearth-370f1.firebasestorage.app',
    measurementId: 'G-9XYTB2M5WR',
  );
}
